### ISSUE TITLE
Getting Server unavailable Error

### ISSUE THREAD

**Issue by jigratz** [MLBAMGames/NHLGames#328] opened 2021-11-01 17:09 UTC
Hello- I absolutely love your NHL games .NET program! I very much prefer it to the chrome front end for streaming NHL games, even thought I have a paid login. Since Friday (10/29/21), I've been receiving a "Server unavailable" error message for all of the games. I was just wondering if anything can be done about this? 
Thank you, 
Joe Gratz
![Server Unavailable](https://user-images.githubusercontent.com/81345856/139711395-71203ba8-2ce8-4778-b0e1-be2c08e70de1.PNG)

**Comment by d-kar** [comment] 2021-11-01 17:18
Duplicate of #326 

For those common issues with easy fixes probably need to add a information on the status bar

**Comment by jigratz** [comment] 2021-11-01 18:18
Doh! I can't believe I didn't try that! Thank you for your help.

**Comment by Rakosnicekk** [comment] 2021-11-02 15:15
What information on the status bar thanks very for answear

**Closed** 2022-11-03 03:39 UTC
